let data = [
  {
    id: 1,
    name: "Lettuce",
    category: "vegetable",
    price: 2.99,
    quantity: 0,
  },
  {
    id: 2,
    name: "Carrot",
    category: "vegetable",
    price: 1.99,
    quantity: 0,
  },
  {
    id: 3,
    name: "Potato",
    category: "vegetable",
    price: 3.99,
    quantity: 20,
  },
  {
    id: 4,
    name: "Tomato",
    category: "vegetable",
    price: 0.99,
    quantity: 35,
  },
  {
    id: 5,
    name: "Broccoli",
    category: "vegetable",
    price: 4.99,
    quantity: 56,
  },
  {
    id: 6,
    name: "Onion",
    category: "vegetable",
    price: 1.49,
    quantity: 5,
  },
  {
    id: 7,
    name: "Premium",
    category: "bread",
    price: 4.99,
    quantity: 15,
  },
  {
    id: 8,
    name: "Burger buns",
    category: "bread",
    price: 2.99,
    quantity: 1,
  },
  {
    id: 9,
    name: "French bread",
    category: "bread",
    price: 3.99,
    quantity: 13,
  },
  {
    id: 10,
    name: "Sandwich bread",
    category: "bread",
    price: 2.49,
    quantity: 20,
  },
  {
    id: 11,
    name: "Mince",
    category: "Meat",
    price: 2.49,
    quantity: 20,
  },
  {
    id: 12,
    name: "Beef",
    category: "Meat",
    price: 9.99,
    quantity: 30,
  },
  {
    id: 13,
    name: "Lamb",
    category: "Meat",
    price: 7.99,
    quantity: 15,
  },
  {
    id: 14,
    name: "Sardine",
    category: "Meat",
    price: 4.99,
    quantity: 3,
  },
  {
    id: 15,
    name: "Dog meat for asians",
    category: "Meat",
    price: 3.99,
    quantity: 0,
  },
  {
    id: 16,
    name: "Mayonnaise",
    category: "spreads",
    price: 1.99,
    quantity: 10,
  },
  {
    id: 17,
    name: "Premium Sauce",
    category: "spreads",
    price: 2.99,
    quantity: 5,
  },
  {
    id: 17,
    name: "Salad dresser",
    category: "spreads",
    price: 2.49,
    quantity: 3,
  },
  {
    id: 18,
    name: "Salt",
    category: "spreads",
    price: 0.99,
    quantity: 20,
  },
];

export default data;
