###
POST http://localhost:8000/api/category
Content-Type: application/json

{
    "categoryName": "haha",
    "link": "www.haha.mn",
    "position": "99"
}

###
GET http://localhost:8000/api/category

###
DELETE  http://localhost:8000/api/category/a71c9fcd-154d-4c47-be77-a5cf3671262e

###
PUT http://localhost:8000/api/category/e2808715-79fb-471c-998f-bdcda3cd7ea5
Content-Type: application/json

{
    "id": "12808715-79fb-471c-998f-bdcda3cd7ea5",
    "categoryName": "hello",
    "link": "hello.com",
    "position":"00"
}


//  ,"categoryName":"1","link":"1","position":"1"