###
POST http://localhost:8000/api/product
Content-Type: application/json

{
    "productName": "something",
    "category": "shoes",
    "isSpecial":"true",
    "position": "1"
}

###
GET http://localhost:8000/api/product



###
GET http://localhost:8000/api/product/bd2c7093-9a5b-4589-865d-08c7df2d232c


###
DELETE  http://localhost:8000/api/product/7ab879b0-d2c2-4d5b-adfa-2c31969273df	

###
PUT http://localhost:8000/api/product/ac172870-7b2c-4f3a-a7da-b852334adec8
Content-Type: application/json

{
    "productName": "bye",
    "category": "bye",
    "isSpecial":"true",
    "position":"45"
}


//  ,"menuName":"1","link":"1","position":"1"