const news = [
  {
    id: "1",
    title: "We know more now than before, and it’s still alarming",
    body: "Understanding Long Covid",
    isTrending: true,
    category: "Mental Health",
    read: "9 min read",
    createdUser: {
      firstName: "Tom Frieden",
      lastName: "Dr",
      userId: "1",
      userImg: require("../images/1_oTq5RWcSwzoDiuAO_OBhaw.png"),
      organization: "Forbes",
    },
    img: require("../images/1_SIrSIkSoOBiUFvv8wIyYgg.png"),
    date: "2022-02-01",
    isSaved: false,
  },
  {
    id: "2",
    title: "We know more now than before, and it’s still alarming",
    body: "Understanding Long Covid",
    isTrending: false,
    category: "Mental Health",
    read: "9 min read",
    createdUser: {
      firstName: "Tom Frieden",
      lastName: "Dr",
      userId: "1",
      userImg: require("../images/1_oTq5RWcSwzoDiuAO_OBhaw.png"),
      organization: "Forbes",
    },
    img: require("../images/1_SIrSIkSoOBiUFvv8wIyYgg.png"),
    date: "2022-05-01",
    isSaved: false,
  },
  {
    id: "3",
    title: "We know more now than before, and it’s still alarming",
    body: "Understanding Long Covid",
    isTrending: false,
    category: "Mental Health",
    read: "9 min read",
    createdUser: {
      firstName: "Tom Frieden",
      lastName: "Dr",
      userId: "1",
      userImg: require("../images/1_oTq5RWcSwzoDiuAO_OBhaw.png"),
      organization: "Forbes",
    },
    img: require("../images/1_SIrSIkSoOBiUFvv8wIyYgg.png"),
    date: "2022-06-01",
    isSaved: false,
  },
  {
    id: "4",
    title: "We know more now than before, and it’s still alarming",
    body: "Understanding Long Covid",
    isTrending: true,
    category: "Technology",
    read: "9 min read",
    createdUser: {
      firstName: "Tom Frieden",
      lastName: "Dr",
      userId: "1",
      userImg: require("../images/1_oTq5RWcSwzoDiuAO_OBhaw.png"),
      organization: "Forbes",
    },
    img: require("../images/1_SIrSIkSoOBiUFvv8wIyYgg.png"),
    date: "2023-01-04",
    isSaved: false,
  },
  {
    id: "5",
    title: "We know more now than before, and it’s still alarming",
    body: "Understanding Long Covid",
    isTrending: true,
    category: "Technology",
    read: "9 min read",
    createdUser: {
      firstName: "Tom Frieden",
      lastName: "Dr",
      userId: "1",
      userImg: require("../images/1_oTq5RWcSwzoDiuAO_OBhaw.png"),
      organization: "Forbes",
    },
    img: require("../images/1_SIrSIkSoOBiUFvv8wIyYgg.png"),
    date: "2023-01-07",
    isSaved: true,
  },
  {
    id: "6",
    title: "Inclusive Design for the 2023 Lunar New Year",
    body: "Hopping and pouncing into the new year with two furry zodiacs",
    isTrending: true,
    category: "Culture",
    read: "7 min read",
    createdUser: {
      firstName: "Leonardo De",
      lastName: "La Rocha",
      userId: "1",
      userImg: require("../images/1_oTq5RWcSwzoDiuAO_OBhaw.png"),
      organization: "Forbes",
    },
    img: "https://miro.medium.com/fit/c/200/134/1*qshjaVzbtHBx5eI0BsH1Gw.png",
    date: "2022-12-25",
    isSaved: true,
  },
  {
    id: "7",
    title: "Diary of a Brand: Blank Street Coffee",
    body: "Blank Street isn’t a coffee shop. It’s a thesis on the future of brand discovery.",
    isTrending: false,
    category: "Branding",
    read: "7 min read",
    createdUser: {
      firstName: "Michelle",
      lastName: "Wiles",
      userId: "1",
      userImg: require("../images/1_oTq5RWcSwzoDiuAO_OBhaw.png"),
      organization: "Forbes",
    },
    img: "https://miro.medium.com/fit/c/200/134/1*l9yQEYry4mPPajh4bLxP_w.jpeg",
    date: "2022-12-22",
    isSaved: true,
  },
  {
    id: "8",
    title: "The new Wikipedia appearance that took the whole village",
    body: "All the other things we changed in addition to Wikipedia’s look",
    isTrending: true,
    category: "Wikipedia",
    read: "8 min read",
    createdUser: {
      firstName: "Jon",
      lastName: "Robson",
      userId: "1",
      userImg: require("../images/1_oTq5RWcSwzoDiuAO_OBhaw.png"),
      organization: "Forbes",
    },
    img: "https://miro.medium.com/fit/c/200/134/1*EYh6l6A7c6ec-PK8AJchTQ.png",
    date: "2023-01-19",
    isSaved: true,
  },
  {
    id: "9",
    title: "the secret ingredient to telling a good story",
    body: "I have this friend who considers himself a professional in his field. When he encounters other professionals acting",
    isTrending: true,
    category: "Videogames",
    read: "52 min read",
    createdUser: {
      firstName: "GB",
      lastName: "Burford",
      userId: "1",
      userImg: require("../images/1_oTq5RWcSwzoDiuAO_OBhaw.png"),
      organization: "Forbes",
    },
    img: "https://miro.medium.com/fit/c/200/134/1*DQnUR6EbK7a0CesOcogDbw.png",
    date: "2023-01-19",
    isSaved: true,
  },
  {
    id: "10",
    title: "Products with Community at Their Core",
    body: "I’ve never understood the concept of “product led growth”. There’s something about how the phrase centres the product",
    isTrending: false,
    category: "Community",
    read: "8 min read",
    createdUser: {
      firstName: "Sarah",
      lastName: "Drinkwater",
      userId: "1",
      userImg: require("../images/1_oTq5RWcSwzoDiuAO_OBhaw.png"),
      organization: "Forbes",
    },
    img: "https://miro.medium.com/fit/c/200/134/0*DKZ3llT04TvWZlLh.png",
    date: "2023-01-13",
    isSaved: true,
  },
  {
    id: "11",
    title: "What We’re Reading: Raising good humans, AI-generated twins, and new year’s",
    body: "A few Medium stories you may have missed lately",
    isTrending: true,
    category: "Community",
    read: "8 min read",
    createdUser: {
      firstName: "Sarah",
      lastName: "Drinkwater",
      userId: "1",
      userImg: require("../images/1_oTq5RWcSwzoDiuAO_OBhaw.png"),
      organization: "Forbes",
    },
    img: "https://miro.medium.com/fit/c/200/134/0*DKZ3llT04TvWZlLh.png",
    date: "2023-01-13",
    isSaved: true,
  },
];

const users = [
  {
    id: 1,
    username: "U00001",
    firstName: "Kylie",
    organization: "Forbes",
    password: "qweqwe",
    type: "superuser",
  },
  {
    id: 2,
    username: "U83901",
    firstName: "John",
    organization: "Forbes",
    password: "qweqwe",
    type: "user",
  },
  {
    id: 3,
    username: "U83902",
    firstName: "Taylor",
    organization: "Forbes",
    password: "qweqwe",
    type: "user",
  },
];

export { news, users };